crds:
  enabled: false

prometheusOperator:
  enabled: true
  admissionWebhooks:
    enabled: true
    patch:
      enabled: true

grafana:
  enabled: true
  service:
    type: LoadBalancer
    port: 80

prometheus:
  enabled: true

alertmanager:
  enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
