crds:
  enabled: false

prometheusOperator:
  enabled: true

prometheus:
  enabled: true

alertmanager:
  enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

grafana:
  enabled: true
  service:
    type: LoadBalancer
    port: 80
